### ISSUE TITLE
Configurable Title

### ISSUE THREAD

**Issue by illegalprime** [HackGT/SponsorshipPortal#29]
Should be able to change the wording of `Sponsorship Portal` to anything else through some configuration, which could mean having a way to change this variable:

https://github.com/HackGT/SponsorshipPortal/blob/master/frontend/src/js/configs.js#L2

and making that variable responsible for every title, including this:

![spectacle a12979](https://user-images.githubusercontent.com/4401220/31447869-0493a654-ae71-11e7-845f-ae616eacb203.png)

This must be a _runtime change_ so the build system should not be able to configure this part.

**Comment by RSLi** [comment]
Seems like this has been fixed a long while ago LOL
