### ISSUE TITLE
Consider moving to MySQL or similar.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/SponsorshipPortal#44]
None of our apps deploy well if they have to have access to persistent storage.
Please consider moving all persistent storage needs out of tiedot & bleve and into a service that can be replicated and clustered, per our redundancy requirements.

Any of the popular DBs should do, maybe there is also one that will store the bleve binary blob but it might just be easier to utilize a DB's text search feature _or_ make a table that maps tokens -> users.

**Comment by bunsenmcdubbs** [comment]
Postgres! Currently in progress

**Comment by bunsenmcdubbs** [comment]
Started with #55. Still need to implement migrations and models

**Comment by bunsenmcdubbs** [comment]
Implementing models in #56

**Comment by illegalprime** [comment]
Closing since #56 was merged.
